### ISSUE TITLE
Not working in vscode

### ISSUE THREAD

**Issue by ruslankonev** [vasilevich/nginxbeautifier#12]
VsCode say — not formatter installed

**Comment by vasilevich** [comment]
perhaps you are mistaken with another module?
perhaps : https://github.com/raynigon/vscode-nginx-formatter   ?

my module doesn't deal directly with vscode, it is entirely formatting focused.

please explain more regarding your issue or post it to the right repo.

**Comment by vasilevich** [comment]
I will close this issue for now, if you think its relevant to my project feel free to reopen.

Good luck.
