### ISSUE TITLE
problem with comment "#" indentation and multiple newline

### ISSUE THREAD

**Issue by ewwink** [vasilevich/nginxbeautifier#2]
try this,
```
server {
listen 80;
server_name localhost;
#charset koi8-r;                                           
}
```

click beautify several time and the results will like
```
server {



  listen 80;
  server_name localhost;
                          #charset koi8-r;                                           
}
```
expected result
```
server {
  listen 80;
  server_name localhost;
  #charset koi8-r;                                           
}

```

**Comment by vasilevich** [comment]
Hello! thank you so much for your input!
the problem has been resolved please try to perform it again.
pay attention that there are now 3 buttons(I think the option you want is in the middle, with "no  newline")
also please be sure to clean your cache if it still doesn't work(I am not sure if thats neccresary)
if you need any more help please do write again good luck!

**Comment by ewwink** [comment]
good work, it solved now.
