### ISSUE TITLE
Second indentation method is not working

### ISSUE THREAD

**Issue by fleaz** [vasilevich/nginxbeautifier#4]
Hi,
on the website there are three buttons to change the indentation style. The second button which should leave out the newline, produces the same result as the first button and always puts a newline after the "server {" line.

I tested this on macOS in Chrome 68 and FF63

Best regards,
Felix

**Comment by vasilevich** [comment]
Hello, thank you for reporting the issue, I will fix it as soon as possible in the following days.

**Comment by vasilevich** [comment]
please if you can, provide a tiny sample of a config you tried running through the website, this would make it easier for me to reproduce exactly the problem,  .

**Comment by f-breidenstein** [comment]
HI @vasilevich,
thanks for the reply.
This happend with any nginx config I tried. So e.g. you can just use the default config which gets shipped with nginx: https://gist.github.com/xameeramir/a5cb675fb6a6a64098365e89a239541d

**Comment by vasilevich** [comment]
seems like this has been fixed, please reopen the issue if it still is relevant.

**Comment by vasilevich** [comment]
@fleaz sorry yes I noticed, I will fix this issue shortly thanks for reporting.

**Comment by vasilevich** [comment]
@fleaz hey I fixed it in the website. cheers.
