### ISSUE TITLE
Tabular formatting?

### ISSUE THREAD

**Issue by erodewald** [vasilevich/nginxbeautifier#6]
Hi, 

Would you considering supporting (or accepting a PR) tabularized formatting? 

### Normal
![image](https://user-images.githubusercontent.com/1534259/45775984-148f3780-bc17-11e8-8cdb-4470cc37e8cf.png)

### Tabular
![image](https://user-images.githubusercontent.com/1534259/45776041-499b8a00-bc17-11e8-8a9f-ea7478b76c80.png)

I don't currently have any idea how you'd implement this but if you didn't want to do it, but would allow it as an option, I'd be happy to learn and contribute.

**Comment by vasilevich** [comment]
@erodewald  hello!
thank you very much for your interest.  yes you are welcome to contribute your code. I will review and fix any problems if there are.  and then with your permission, publish it aswell into the nginxbeautifier.com website.
I will be happy to get any help. if you have any problems let me know.
