### ISSUE TITLE
end of line comment breaks

### ISSUE THREAD

**Issue by lukasa1993** [vasilevich/nginxbeautifier#9]
```
server {
    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # testing comment line


        server_name example.com;
    listen 80;
    return 404; # testing comment line


}
```

this is transformed into

```
server
{
	if ($host = example.com)
	{
		return 301 https://$host$request_uri;
		} # testing comment lin
	}
	# testing comment line


	server_name example.com;
	listen 80;
	return 404; # testing comment line


}
```

**Comment by lukasa1993** [comment]
same happens with https://github.com/denysvitali/nginxbeautify this as well

**Comment by vasilevich** [comment]
hello @lukasa1993 I am sorry I don't understand the issue, 

can you please post the results you wish to recieve aswell?  or mark in paint or something what exactly is wrong.

thanks!

**Comment by lukasa1993** [comment]
there is early } which breaks syntax is closes server scope after if

**Comment by vasilevich** [comment]
@lukasa1993 Hello! I fixed the issue mentioned, I did not yet update nginxbeautifier.com  but I pushed the npm module with up to date fix.

please reopen this issue if its not resolved, or open a new issue if you need anything else.
